"""upgrade

Revision ID: 14148bf11d3a
Revises: 42f3f25b25be
Create Date: 2026-03-07 19:11:39.271641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14148bf11d3a'
down_revision: Union[str, Sequence[str], None] = '42f3f25b25be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['table_users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['table_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['table_chats.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['table_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_messages')
    op.drop_table('table_chats')
    # ### end Alembic commands ###
