"""fix 2

Revision ID: 3bdac4eff8f7
Revises: a171ea974b5e
Create Date: 2026-03-07 12:21:29.254794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdac4eff8f7'
down_revision: Union[str, Sequence[str], None] = 'a171ea974b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('sub_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sub_user'], ['table_users.id'], ),
    sa.ForeignKeyConstraint(['user'], ['table_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_sub')
    # ### end Alembic commands ###
