"""sosal?

Revision ID: 5e3e1ec2dbcc
Revises: eee0d756a056
Create Date: 2026-03-18 14:10:28.752412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3e1ec2dbcc'
down_revision: Union[str, Sequence[str], None] = 'eee0d756a056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_users', sa.Column('avatar', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_users', 'avatar')
    # ### end Alembic commands ###
