"""hz

Revision ID: eee0d756a056
Revises: 14148bf11d3a
Create Date: 2026-03-07 20:25:19.933243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee0d756a056'
down_revision: Union[str, Sequence[str], None] = '14148bf11d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chat_user_pair', 'table_chats', ['user1_id', 'user2_id'])
    op.create_index(op.f('ix_table_messages_chat_id'), 'table_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_table_messages_created_at'), 'table_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_messages_created_at'), table_name='table_messages')
    op.drop_index(op.f('ix_table_messages_chat_id'), table_name='table_messages')
    op.drop_constraint('uq_chat_user_pair', 'table_chats', type_='unique')
    # ### end Alembic commands ###
